### ISSUE TITLE
Sobre os vídeos

### ISSUE THREAD

**Issue by NKKFu** [desenvolva-me/curso-javascript-basico#1]
Sensacional a ideia de vocês! Assim que criaram este repositório, já mandei links para os meus amigos já ficarem de olho também, tenho certeza que vai dar bom hehe. Mas ficou algumas dúvidas em relação ao projeto, como:

- Quais frameworks js serão utilizados?
- Será ao vivo?
- Quando será?

Ansioso para os primeiros vídeos do curso no canal, parabéns pela iniciativa de vocês.

**Comment by NicolasLopes7** [comment]
Fala @NKKFu, nossa ideia é fazermos vários cursos, começando assim com Javascript Básico, mini cursos como de git, e avançando o conhecimento em JS em trilhas: Front End, Design, Web, Backend... Quanto aos frameworks, não gostamos de se prender a uma tecnologia, mas na desenvolva.me utilizamos bastante React para Web, React Native para Mobile, e Express para backend, mas com certeza teremos vídeos com adonis, nest e quem sabe até Vue! Quanto a data estamos produzindo, mas garanto que em breve começaremos! Abraço.
